### ISSUE TITLE
Sometimes AutoTunerTest.testAllConfigurations fails (not deterministic)

### ISSUE THREAD

**Issue by Garfield96** [AutoPas/AutoPas#199] opened 2019-05-03 20:44 UTC
**Describe the bug**
Sometimes AutoTunerTest.testAllConfigurations fails. This behaviour is not deterministic.

**To Reproduce**
Steps to reproduce the behaviour:
1. build runTests
2. run tests

**Expected behaviour**
Both configurations should be unequal.

**Test output**
```
Note: Google Test filter = AutoTunerTest.testAllConfigurations
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AutoTunerTest
[ RUN      ] AutoTunerTest.testAllConfigurations
/mnt/c/Users/chris/OneDrive/Studium/Bachelorarbeit/AutoPas/tests/testAutopas/tests/selectors/AutoTunerTest.cpp:51: Failure
Expected: (currentConfig) != (prevConfig), actual: 16-byte object <04-00 00-00 03-00 00-00 01-00 00-00 01-00 00-00> vs 16-byte object <04-00 00-00 03-00 00-00 01-00 00-00 01-00 00-00>
currentConf: {Container: VerletClusterLists , Traversal: c01 , Data Layout: Structure-of-Arrays , Newton 3: disabled} == prevConfig: {Container: VerletClusterLists , Traversal: c01 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
[  FAILED  ] AutoTunerTest.testAllConfigurations (3 ms)
[----------] 1 test from AutoTunerTest (3 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (3 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AutoTunerTest.testAllConfigurations

 1 FAILED TEST
<end of output>
Test time =   0.06 sec
```

**Build environment:**
 - OS: WSL - Debian (this is not the default WSL, standard WSL is build upon Ubuntu)
 - Compiler: gcc 6.3.0
 - Build System: cmake 3.13.2, GNU make 4.1 
 - same error occurred on different hardware (laptop as well as desktop PC)

**Additional context**
Till now, this error only occurred in branch "linked-cells-smaller-cell-sizes", but its quite unlikely that the changes done in this branch break this test case.

**Comment by SteffenSeckler** [comment] 2019-05-07 08:03
looks like an error that only happens in your branch. will check whether I can reproduce it.

**Comment by SteffenSeckler** [comment] 2019-05-07 08:09
could you tell me the cmake options you used? openmp and such

**Comment by Garfield96** [comment] 2019-05-07 10:38
cmake options:
```
BUILD_EXAMPLES:BOOL=ON
BUILD_TARGET_DOC:BOOL=ON
BUILD_TESTS:BOOL=ON
CLANG_FORMAT:FILEPATH=/usr/bin/clang-format-6.0
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=RELEASE
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/lib/ccache/c++
CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-6
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-6
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/lib/ccache/cc
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-6
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-6
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CodeCoverage:BOOL=OFF
DOXYGEN_DIA_EXECUTABLE:FILEPATH=DOXYGEN_DIA_EXECUTABLE-NOTFOUND
DOXYGEN_DOT_EXECUTABLE:FILEPATH=/usr/bin/dot
DOXYGEN_EXECUTABLE:FILEPATH=/usr/bin/doxygen
DOXYGEN_MSCGEN_EXECUTABLE:FILEPATH=DOXYGEN_MSCGEN_EXECUTABLE-NOTFOUND
ENABLE_ADDRESS_SANITIZER:BOOL=OFF
ENABLE_CLANG_TIDY:BOOL=OFF
ENABLE_CUDA:BOOL=OFF
ENABLE_FAST_MATH:BOOL=OFF
ENABLE_MEMORY_SANITIZER:BOOL=OFF
ENABLE_THREAD_SANITIZER:BOOL=OFF
MPIEXEC_EXECUTABLE:FILEPATH=MPIEXEC_EXECUTABLE-NOTFOUND
MPIEXEC_MAX_NUMPROCS:STRING=2
MPIEXEC_NUMPROC_FLAG:STRING=-n
MPIEXEC_POSTFLAGS:STRING=
MPIEXEC_PREFLAGS:STRING=
MPI_CXX_ADDITIONAL_INCLUDE_DIRS:STRING=
MPI_CXX_COMPILER:FILEPATH=MPI_CXX_COMPILER-NOTFOUND
MPI_CXX_COMPILE_DEFINITIONS:STRING=
MPI_CXX_COMPILE_OPTIONS:STRING=
MPI_CXX_HEADER_DIR:PATH=MPI_CXX_HEADER_DIR-NOTFOUND
MPI_CXX_LIB_NAMES:STRING=
MPI_CXX_LINK_FLAGS:STRING=
MPI_CXX_SKIP_MPICXX:BOOL=FALSE
MPI_C_ADDITIONAL_INCLUDE_DIRS:STRING=
MPI_C_COMPILER:FILEPATH=MPI_C_COMPILER-NOTFOUND
MPI_C_COMPILE_DEFINITIONS:STRING=
MPI_C_COMPILE_OPTIONS:STRING=
MPI_C_HEADER_DIR:PATH=MPI_C_HEADER_DIR-NOTFOUND
MPI_C_LIB_NAMES:STRING=
MPI_C_LINK_FLAGS:STRING=
OPENMP:BOOL=OFF
USE_VECTORIZATION:BOOL=ON
VECTOR_INSTRUCTIONS:STRING=NATIVE
VERBOSE_LOGGING:BOOL=OFF
spdlog_DIR:PATH=spdlog_DIR-NOTFOUND

```

**Comment by SteffenSeckler** [comment] 2019-05-08 14:28
fixed in https://github.com/AutoPas/AutoPas/commit/7fea3bfa4d1764f046f9720c6eb489805d65b49c

**Closed by SteffenSeckler** 2019-05-08 14:28 UTC
Labels: bug, tests
